name: validate webapp
on: workflow_dispatch
jobs:
  sanitytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: setup jdk
        uses: actions/checkout@v1
        with:
          java-version: 11
      - name: run with maven
        run: |
             mvn clean test -Dtestng="testng.xml" -DbrowserType="chrome"
  
